name: Deis
url: http://deis.io
baseurl: /deis.io
tagline: Your Paas. Your Rules.
pygments: true
gems:
  - jemoji
markdown: redcarpet
redcarpet:
  extensions: [ "no_intra_emphasis",
                "fenced_code_blocks",
                "autolink",
                "tables",
                "with_toc_data",
                "strikethrough",
                "space_after_headers",
                "superscript"
              ]
timezone: America/Denver
permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: "\n"
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.ruby-version']
authors:
  mboersma:
    display_name: Matt Boersma
    gravatar: 599d83c3405e24cae65a1b1ad5401cb2
    short_bio: Senior Software Engineer at OpDemand
    twitter: RealMattBoersma
  bacongobbler:
    display_name: Matt Fisher
    gravatar: 65e1d16c6d56dd57fa47b30dcb429eed
    short_bio: Senior Software Engineer at OpDemand
    twitter: bacongobbler
  gabrtv:
    display_name: Gabriel Monroy
    gravatar: 1f5dd69ca86e92ce3bc039c63f511d40
    short_bio: Cloud operations nerd and CTO at OpDemand
    twitter: gabrtv
  bengrunfeld:
    display_name: Ben Grunfeld
    gravatar: 1f1cd2ad7176acf859cbbbed23554fc9
    short_bio: Software Engineer and Front End Developer at OpDemand
    twitter: bengrunfeld
